version: '3.8'

services:
  maquina1:
    build: ./maquina
    container_name: maquina1
    networks:
      - redinfra

  maquina2:
    build: ./maquina
    container_name: maquina2
    networks:
      - redinfra

  maquina3:
    build: ./maquina
    container_name: maquina3
    networks:
      - redinfra

  backup:
    build: ./backup
    container_name: backup
    volumes:
      - backup_storage:/home/backups
    networks:
      - redinfra

  explorador:
    build: ./explorador
    container_name: explorador
    ports:
      - "8080:80"
    volumes:
      - backup_storage:/mnt/backups:ro
      - alertas:/home/alertas_detectadas
    networks:
      - redinfra

volumes:
  backup_storage:
  alertas:

networks:
  redinfra:
